"use client"

import { useMemo } from "react"
import { format } from "date-fns"
import type { ColumnDef } from "@tanstack/react-table"
import { DownloadIcon, FileTextIcon } from "lucide-react"
import { PageHeader } from "@/components/common/page-header"
import { DataTable } from "@/components/tables/data-table"
import { DataTableColumnHeader } from "@/components/tables/data-table-column-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { PORTAL_DOCUMENTS, PORTAL_PATIENT, type PortalDocument } from "@/lib/mock/portal"

function downloadDocument(doc: PortalDocument) {
  const lines = [
    "Folio Health EMR",
    doc.title,
    `Patient: ${PORTAL_PATIENT.name} (${PORTAL_PATIENT.mrn})`,
    `Category: ${doc.category}`,
    `Date: ${format(new Date(doc.date), "MMM d, yyyy")}`,
    "",
    "This is a placeholder document generated by the Folio Health EMR patient portal.",
  ].join("\n")
  const blob = new Blob([lines], { type: "text/plain" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${doc.id}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

function PortalDownloads() {
  const columns = useMemo<ColumnDef<PortalDocument>[]>(
    () => [
      {
        accessorKey: "title",
        header: ({ column }) => <DataTableColumnHeader column={column} title="Document" />,
        cell: ({ row }) => (
          <div className="flex items-center gap-2.5">
            <div className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <FileTextIcon className="size-4" />
            </div>
            <span className="font-medium text-foreground">{row.original.title}</span>
          </div>
        ),
      },
      {
        accessorKey: "category",
        header: "Category",
        cell: ({ row }) => <Badge variant="outline">{row.original.category}</Badge>,
      },
      {
        accessorKey: "date",
        header: ({ column }) => <DataTableColumnHeader column={column} title="Date" />,
        cell: ({ row }) => (
          <span className="text-muted-foreground">{format(new Date(row.original.date), "MMM d, yyyy")}</span>
        ),
      },
      {
        accessorKey: "sizeKb",
        header: "Size",
        cell: ({ row }) => (
          <span className="tabular-nums text-muted-foreground">{row.original.sizeKb} KB</span>
        ),
      },
      {
        id: "actions",
        header: "",
        cell: ({ row }) => (
          <Button
            variant="outline"
            size="sm"
            className="gap-1.5"
            onClick={() => downloadDocument(row.original)}
          >
            <DownloadIcon className="size-3.5" />
            Download
          </Button>
        ),
      },
    ],
    []
  )

  return (
    <div>
      <PageHeader title="Downloads" description="Discharge summaries, lab reports, invoices, and prescriptions" />

      <DataTable
        columns={columns}
        data={PORTAL_DOCUMENTS}
        emptyTitle="No documents yet"
        emptyDescription="Documents generated for your visits will appear here for download."
      />
    </div>
  )
}

export { PortalDownloads }
